name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
        id: go

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Go build
        run: go build -v ./...
