name: Lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  golangci:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.19

      - name: Run
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
