name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pycodestyle

      - name: Run pylint
        continue-on-error: true
        run: |
          pylint $(git ls-files '*.py')

      - name: Run pycodestyle
        continue-on-error: true
        run: |
          pycodestyle --show-source --show-pep8 $(git ls-files '*.py')
